---
# tasks for deploy backup script and adding cron job

- name: mking directory for backup
  file:
    path: "/opt/backup"
    recurse: yes
    owner: "root"
    mode: 0644
    state: directory

- name: Touch a file for metriks
  file:
    path: /var/lib/node_exporter/textfile_collector/backups.prom
    state: touch

- name: copy script for cron
  template: src=backup.sh.j2 dest=/opt/backup/backup.sh owner=root group=root mode=0644
  tags: deploy_script

- name: Creates weekly backup cronjob
  cron: minute="0" hour="2"
        name="Making backup on this server"
        user="root"
        job="sh /opt/backup/backup.sh"
