---
# tasks file for deploy ssh pub key

- name: copy auth keys of user
  template: src=authorized_keys.j2 dest=~/.ssh/authorized_keys owner=root group=root mode=0644
  tags: sshkey

- name: copy sshd config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0600
  tags: sshconfig

- firewalld:
    zone: public
    port: 9122/tcp 
    permanent: yes
    state: enabled
  tags: sshconfig

- firewalld:
    service: ssh
    permanent: yes
    state: disabled
  tags: sshconfig

- systemd:
    name: firewalld
    state: restarted
  tags: sshconfig

- systemd:
    name: sshd
    state: restarted
  tags: sshconfig
