- name: Add yum repository
  yum_repository:
    name: prometheus
    description: prometheus yum repo
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch
    gpgkey: https://packagecloud.io/prometheus-rpm/release/gpgkey
    gpgcheck: no

- name: Install node_exporter
  dnf:
    name: node_exporter
    state: present

- name: enable service node_exporter server
  systemd:
    name: node_exporter
    enabled: yes
    masked: no

- name: node_exporter server start
  systemd:
    state: started
    name: node_exporter

- name: Add port to firewalld
  firewalld:
    port: 9100/tcp
    permanent: yes
    state: enabled
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
 
- name: reload service firewalld
  systemd:
   name: firewalld
   state: reloaded